fos_rest:
    view:
        formats:
            json: true
        failed_validation: HTTP_BAD_REQUEST
        serialize_null: true
    routing_loader: false
    serializer:
        serialize_null: true
