app_api_index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [GET]

app_api_products:
    resource: api/products.yaml
    prefix: /products

app_api_cart:
    resource: api/cart.yaml
    prefix: /cart
