app_api_index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [GET]

app_api_index_test:
    path: /test
    controller: App\Controller\IndexController::test
    methods: [POST]
